---
- name: Tomcat deployment playbook
  hosts: tomcat-nodes 
  become: yes        
  become_method: sudo
  remote_user: vagrant
  vars:
    tomcat_ver: 9.0.52
    ui_manager_user: vagrant 
    ui_manager_pass: vagrant
    ui_admin_username: vagrant 
    ui_admin_pass: vagrant    
  roles:
    - tomcat

