---
- name: Copy sample WAR file to Tomcat Server
  copy:
    src: sample.war
    dest: "{{ dest }}"
    owner: tomcat
    group: tomcat

- name: Download magnolia WAR file on the Tomcat Server
  get_url:
    url: https://sourceforge.net/projects/magnolia/files/latest/download
    dest: "{{ dest }}/magnolia.war"
    owner: tomcat
    group: tomcat
